apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-operator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: zookeeper-operator
    spec:
      containers:
      - name: zookeeper-operator
        image: zookeeper-operator:0.1.0
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args: ["--namespace=$MY_POD_NAMESPACE"]